### ISSUE TITLE
Checking if JSON array in response contains POJO

### ISSUE THREAD

**Issue by Angus-Young** [underlandxyz/fb-sprint-2-4#7]
In RestAssured, how can I use their builder to check that an array contained within a JSON response contains a specific java object.

**Comment by stdlibdoh** [comment]
https://github.com/rest-assured/rest-assured/wiki/Usage#deserialization

**Comment by Angus-Young** [comment]
I've read the docs, this is applicable for getting a like for like deserialization, but in my case I need to deserialize a json array, which can be done if I want to get a linked hashmap, but then I need to use an object mapper and map the set to get a single java object back, which seems like a lot of work to just check if an object is present. It also means I have to break out of the RestAssured builder and use plain JUnit asserts to compare the final object with my expected object, in which case there would be no point using RestAssured in the first place.

**Comment by Angus-Young** [comment]
@stdlibdoh 


    public void find_book_by_id_existing() throws Exception {
        Book book = new Book(1, "Ziggy Stardust", "A Ballsy Orignal Work", new Date());
        bookRepository.save(book);

        given().
        when().
                get("/book/find?id=" + book.getId()).
        then().
                assertThat().
                contentType(ContentType.JSON).
                statusCode(200).
                body("size()", is(1));

        // should also check that returned json array contains the expected book

    }

**Comment by Angus-Young** [comment]
Resolved with JSON field acccessors
